# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='deadline',
            field=models.DateField(default=None, verbose_name='deadline'),
        ),
        migrations.AddField(
            model_name='item',
            name='orderNumber',
            field=models.IntegerField(default=1),
        ),
    ]
